/**
 * Build-time generator for the external-tools catalog.
 *
 * Reads every `data/external-tools/*.json` file, validates and normalises it
 * against `externalToolSchema`, and emits `lib/data/external-tools.generated.ts`
 * — a plain `ExternalTool[]` that the rest of the app imports synchronously.
 *
 * Run via `npm run gen:tools` (also wired into `predev` / `prebuild`). CI runs
 * it and fails if the committed generated file is stale, so a contributor only
 * has to add a JSON file — never hand-edit generated TypeScript.
 *
 * Invalid input (bad URL, unknown category, malformed id, …) throws here with a
 * clear file path, so a broken tool entry can never reach the bundle.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { parseExternalTool } from '../lib/external-tool.schema';
import { ExternalToolCategory, type ExternalTool } from '../lib/types';

/** Map each category string value back to its `ExternalToolCategory.KEY` source form. */
const CATEGORY_TO_ENUM = new Map<string, string>(
  (Object.entries(ExternalToolCategory) as [string, string][]).map(([key, value]) => [
    value,
    `ExternalToolCategory.${key}`,
  ]),
);

const ROOT = resolve(__dirname, '..');
const DATA_DIR = join(ROOT, 'data', 'external-tools');
const OUT_FILE = join(ROOT, 'lib', 'data', 'external-tools.generated.ts');

function loadTools(): ExternalTool[] {
  const files = readdirSync(DATA_DIR)
    .filter((f) => f.endsWith('.json'))
    .sort(); // deterministic generation order (display order is via sortOrder)

  const seen = new Map<string, string>();
  const tools: ExternalTool[] = [];

  files.forEach((file, index) => {
    const path = join(DATA_DIR, file);
    let raw: unknown;
    try {
      raw = JSON.parse(readFileSync(path, 'utf8'));
    } catch (err) {
      throw new Error(`Invalid JSON in data/external-tools/${file}: ${(err as Error).message}`);
    }

    let tool: ExternalTool;
    try {
      tool = parseExternalTool(raw, index);
    } catch (err) {
      throw new Error(`Schema validation failed for data/external-tools/${file}:\n${(err as Error).message}`);
    }

    const expectedFile = `${tool.id}.json`;
    if (file !== expectedFile) {
      throw new Error(`data/external-tools/${file}: filename must match id ("${expectedFile}").`);
    }
    if (seen.has(tool.id)) {
      throw new Error(`Duplicate tool id "${tool.id}" in ${file} (also in ${seen.get(tool.id)}).`);
    }
    seen.set(tool.id, file);
    tools.push(tool);
  });

  if (tools.length === 0) {
    throw new Error(`No tool JSON files found in ${DATA_DIR}.`);
  }
  return tools;
}

function renderTool(tool: ExternalTool): string {
  const categories = tool.categories
    .map((c) => CATEGORY_TO_ENUM.get(c) ?? `'${c}'`)
    .join(', ');
  return `  {
    id: ${JSON.stringify(tool.id)},
    name: ${JSON.stringify(tool.name)},
    description: ${JSON.stringify(tool.description)},
    categories: [${categories}],
    inputs: ${JSON.stringify(tool.inputs)},
    outputs: ${JSON.stringify(tool.outputs)},
    host: ${JSON.stringify(tool.host)},
    url: ${JSON.stringify(tool.url)},
    featured: ${tool.featured ? 'true' : 'false'},
    sortOrder: ${tool.sortOrder},
  },`;
}

function render(tools: ExternalTool[]): string {
  return `// AUTO-GENERATED by scripts/gen-external-tools.ts — do not edit by hand.
// Add or change a tool by editing data/external-tools/<id>.json, then run \`npm run gen:tools\`.
import { ExternalTool, ExternalToolCategory } from '@/lib/types';

export const externalTools: ExternalTool[] = [
${tools.map(renderTool).join('\n')}
];
`;
}

function main() {
  const tools = loadTools();
  writeFileSync(OUT_FILE, render(tools), 'utf8');
  console.log(`Generated ${tools.length} external tools → lib/data/external-tools.generated.ts`);
}

main();
